baseURL: /
theme: hugo-apero
languageCode: en
title: home
author: Alison Hill
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  #favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  #logo: /img/blogophonic-mark-dark.png
  mainSections:
    - podcast
    - project
    - talk
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/jpflores-13
    - icon: facebook-square
      icon_pack: fab
      url: https://www.facebook.com/jp.flores.14/
    - icon: instagram
      icon_pack: fab
      url: https://www.instagram.com/jpflores_31/
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/jpflores_31
    - icon: orcid
      icon_pack: ai
      url: http://orcid.org/0000-0002-8082-1890
    - icon: rss
      icon_pack: fas
      url: /blog/index.xml
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
  twitter: apreshill
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: apreshill/apero
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
    - name: Contributors
      title: Contributors
      url: /contributors/
      weight: 3
  header:
    - name: About
      title: About Blogophonic
      url: /about/
      weight: 1
    - name: podcast
      title: podcast
      url: /blog/
      weight: 2
    - name: projects
      title: project portfolio
      url: /project/
      weight: 3
    - name: elements
      title: elements
      url: /elements/
      weight: 4
    - name: cv/resume
      title: cv/resume
      url: /collection/
      weight: 5
    - name: contact
      title: contact
      url: /form/
      weight: 6
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
